/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignee { 'principal' : Principal, 'name' : string }
export interface Bucket {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
}
export interface CompanyEntry {
  'id' : bigint,
  'website_url' : string,
  'password' : string,
  'name' : string,
  'category' : CompanyEntryCategory,
}
export type CompanyEntryCategory = { 'labs' : null } |
  { 'insurance' : null } |
  { 'dental_supply' : null };
export interface Invite {
  'status' : InviteStatus,
  'token' : string,
  'createdAt' : Time,
}
export type InviteStatus = { 'active' : null } |
  { 'revoked' : null } |
  { 'used' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'senderName' : string,
}
export interface PrivateMessage {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface ResourceCategory { 'id' : bigint, 'name' : string }
export interface ResourceEntry {
  'id' : bigint,
  'url' : string,
  'categoryId' : bigint,
  'password' : string,
  'name' : string,
}
export interface Task {
  'id' : bigint,
  'assignee' : Assignee,
  'title' : string,
  'creator' : Principal,
  'completed' : boolean,
  'bucketId' : [] | [bigint],
  'description' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'lastSeen' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCompanyEntry' : ActorMethod<
    [string, CompanyEntryCategory, string, string],
    undefined
  >,
  'addMessage' : ActorMethod<[string], undefined>,
  'addResourceEntry' : ActorMethod<[bigint, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBucket' : ActorMethod<[string, string], undefined>,
  'createInvite' : ActorMethod<[], string>,
  'createResourceCategory' : ActorMethod<[string], undefined>,
  'createTask' : ActorMethod<
    [string, string, Assignee, [] | [bigint]],
    undefined
  >,
  'deleteBucket' : ActorMethod<[bigint], undefined>,
  'deleteCompanyEntry' : ActorMethod<[bigint], undefined>,
  'deleteResourceCategory' : ActorMethod<[bigint], undefined>,
  'deleteResourceEntry' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'editResourceEntry' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'editTask' : ActorMethod<[bigint, string, string, [] | [bigint]], undefined>,
  'getBuckets' : ActorMethod<[], Array<Bucket>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyEntries' : ActorMethod<[], Array<CompanyEntry>>,
  'getDirectMessagesWith' : ActorMethod<[Principal], Array<PrivateMessage>>,
  'getInvites' : ActorMethod<[], Array<Invite>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getResourceCategories' : ActorMethod<[], Array<ResourceCategory>>,
  'getResourceEntries' : ActorMethod<[], Array<ResourceEntry>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveTaskToResourceCategory' : ActorMethod<[bigint, bigint], undefined>,
  'register' : ActorMethod<[string, string], undefined>,
  'renameBucket' : ActorMethod<[bigint, string], undefined>,
  'renameResourceCategory' : ActorMethod<[bigint, string], undefined>,
  'revokeInvite' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPrivateMessage' : ActorMethod<[Principal, string], undefined>,
  'toggleTaskCompleted' : ActorMethod<[bigint], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
  'updateTask' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];