/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyEntryCategory = IDL.Variant({
  'labs' : IDL.Null,
  'insurance' : IDL.Null,
  'dental_supply' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignee = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const Bucket = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastSeen' : Time });
export const CompanyEntry = IDL.Record({
  'id' : IDL.Nat,
  'website_url' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'category' : CompanyEntryCategory,
});
export const PrivateMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const InviteStatus = IDL.Variant({
  'active' : IDL.Null,
  'revoked' : IDL.Null,
  'used' : IDL.Null,
});
export const Invite = IDL.Record({
  'status' : InviteStatus,
  'token' : IDL.Text,
  'createdAt' : Time,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const ResourceCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
});
export const ResourceEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'categoryId' : IDL.Nat,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'assignee' : Assignee,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'completed' : IDL.Bool,
  'bucketId' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCompanyEntry' : IDL.Func(
      [IDL.Text, CompanyEntryCategory, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addMessage' : IDL.Func([IDL.Text], [], []),
  'addResourceEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBucket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createInvite' : IDL.Func([], [IDL.Text], []),
  'createResourceCategory' : IDL.Func([IDL.Text], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Assignee, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'deleteBucket' : IDL.Func([IDL.Nat], [], []),
  'deleteCompanyEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteResourceCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteResourceEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'editCompanyEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editResourceEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'getBuckets' : IDL.Func([], [IDL.Vec(Bucket)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyEntries' : IDL.Func([], [IDL.Vec(CompanyEntry)], ['query']),
  'getDirectMessagesWith' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getInvites' : IDL.Func([], [IDL.Vec(Invite)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getResourceCategories' : IDL.Func(
      [],
      [IDL.Vec(ResourceCategory)],
      ['query'],
    ),
  'getResourceEntries' : IDL.Func([], [IDL.Vec(ResourceEntry)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveTaskToResourceCategory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'renameBucket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'renameResourceCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'revokeInvite' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'toggleTaskCompleted' : IDL.Func([IDL.Nat], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyEntryCategory = IDL.Variant({
    'labs' : IDL.Null,
    'insurance' : IDL.Null,
    'dental_supply' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignee = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const Bucket = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastSeen' : Time });
  const CompanyEntry = IDL.Record({
    'id' : IDL.Nat,
    'website_url' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'category' : CompanyEntryCategory,
  });
  const PrivateMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const InviteStatus = IDL.Variant({
    'active' : IDL.Null,
    'revoked' : IDL.Null,
    'used' : IDL.Null,
  });
  const Invite = IDL.Record({
    'status' : InviteStatus,
    'token' : IDL.Text,
    'createdAt' : Time,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const ResourceCategory = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const ResourceEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'categoryId' : IDL.Nat,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'assignee' : Assignee,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'completed' : IDL.Bool,
    'bucketId' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCompanyEntry' : IDL.Func(
        [IDL.Text, CompanyEntryCategory, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addMessage' : IDL.Func([IDL.Text], [], []),
    'addResourceEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBucket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createInvite' : IDL.Func([], [IDL.Text], []),
    'createResourceCategory' : IDL.Func([IDL.Text], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Assignee, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'deleteBucket' : IDL.Func([IDL.Nat], [], []),
    'deleteCompanyEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteResourceCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteResourceEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'editCompanyEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editResourceEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'getBuckets' : IDL.Func([], [IDL.Vec(Bucket)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyEntries' : IDL.Func([], [IDL.Vec(CompanyEntry)], ['query']),
    'getDirectMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getInvites' : IDL.Func([], [IDL.Vec(Invite)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getResourceCategories' : IDL.Func(
        [],
        [IDL.Vec(ResourceCategory)],
        ['query'],
      ),
    'getResourceEntries' : IDL.Func([], [IDL.Vec(ResourceEntry)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveTaskToResourceCategory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'renameBucket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'renameResourceCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'revokeInvite' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'toggleTaskCompleted' : IDL.Func([IDL.Nat], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };