/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Assignee = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastSeen' : Time });
export const PrivateMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'assignee' : Assignee,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, Assignee], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectMessagesWith' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Assignee = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'lastSeen' : Time });
  const PrivateMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'assignee' : Assignee,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, Assignee], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPrivateMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateTask' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };