/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Invite {
    status: InviteStatus;
    token: string;
    createdAt: Time;
}
export interface Task {
    id: bigint;
    assignee: Assignee;
    title: string;
    creator: Principal;
    completed: boolean;
    bucketId?: bigint;
    description: string;
    timestamp: Time;
}
export interface ResourceEntry {
    id: bigint;
    url: string;
    categoryId: bigint;
    username: string;
    password: string;
    name: string;
}
export interface PrivateMessage {
    id: bigint;
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: Time;
}
export interface Bucket {
    id: bigint;
    name: string;
    createdAt: Time;
    color: string;
}
export interface CompanyEntry {
    id: bigint;
    website_url: string;
    username: string;
    password: string;
    name: string;
    category: CompanyEntryCategory;
}
export interface Assignee {
    principal: Principal;
    name: string;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    timestamp: Time;
    senderName: string;
}
export interface ResourceCategory {
    id: bigint;
    name: string;
}
export interface UserProfile {
    name: string;
    lastSeen: Time;
}
export enum CompanyEntryCategory {
    labs = "labs",
    insurance = "insurance",
    dental_supply = "dental_supply"
}
export enum InviteStatus {
    active = "active",
    revoked = "revoked",
    used = "used"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCompanyEntry(name: string, category: CompanyEntryCategory, website_url: string, username: string, password: string): Promise<void>;
    addMessage(content: string): Promise<void>;
    addResourceEntry(categoryId: bigint, name: string, url: string, username: string, password: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBucket(name: string, color: string): Promise<void>;
    createInvite(): Promise<string>;
    createResourceCategory(name: string): Promise<void>;
    createTask(title: string, description: string, assignee: Assignee, bucketId: bigint | null): Promise<void>;
    deleteBucket(id: bigint): Promise<void>;
    deleteCompanyEntry(id: bigint): Promise<void>;
    deleteResourceCategory(id: bigint): Promise<void>;
    deleteResourceEntry(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    editCompanyEntry(id: bigint, name: string, website_url: string, username: string, password: string): Promise<void>;
    editResourceEntry(id: bigint, name: string, url: string, username: string, password: string): Promise<void>;
    editTask(id: bigint, title: string, description: string, bucketId: bigint | null): Promise<void>;
    getBuckets(): Promise<Array<Bucket>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyEntries(): Promise<Array<CompanyEntry>>;
    getDirectMessagesWith(partner: Principal): Promise<Array<PrivateMessage>>;
    getInvites(): Promise<Array<Invite>>;
    getMessages(): Promise<Array<Message>>;
    getResourceCategories(): Promise<Array<ResourceCategory>>;
    getResourceEntries(): Promise<Array<ResourceEntry>>;
    getTasks(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfiles(): Promise<Array<UserProfile>>;
    isCallerAdmin(): Promise<boolean>;
    moveTaskToResourceCategory(taskId: bigint, resourceCategoryId: bigint): Promise<void>;
    register(name: string, inviteToken: string): Promise<void>;
    renameBucket(id: bigint, newName: string): Promise<void>;
    renameResourceCategory(id: bigint, newName: string): Promise<void>;
    revokeInvite(token: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendPrivateMessage(recipient: Principal, content: string): Promise<void>;
    toggleTaskCompleted(taskId: bigint): Promise<void>;
    updateLastSeen(): Promise<void>;
    updateTask(id: bigint, completed: boolean): Promise<void>;
}
import type { Assignee as _Assignee, CompanyEntry as _CompanyEntry, CompanyEntryCategory as _CompanyEntryCategory, Invite as _Invite, InviteStatus as _InviteStatus, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCompanyEntry(arg0: string, arg1: CompanyEntryCategory, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCompanyEntry(arg0, to_candid_CompanyEntryCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCompanyEntry(arg0, to_candid_CompanyEntryCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async addMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0);
            return result;
        }
    }
    async addResourceEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResourceEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResourceEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBucket(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBucket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBucket(arg0, arg1);
            return result;
        }
    }
    async createInvite(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvite();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvite();
            return result;
        }
    }
    async createResourceCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createResourceCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResourceCategory(arg0);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: Assignee, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteBucket(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBucket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBucket(arg0);
            return result;
        }
    }
    async deleteCompanyEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompanyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompanyEntry(arg0);
            return result;
        }
    }
    async deleteResourceCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResourceCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResourceCategory(arg0);
            return result;
        }
    }
    async deleteResourceEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResourceEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResourceEntry(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async editCompanyEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCompanyEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCompanyEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async editResourceEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editResourceEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editResourceEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async editTask(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTask(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTask(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getBuckets(): Promise<Array<Bucket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuckets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuckets();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyEntries(): Promise<Array<CompanyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyEntries();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyEntries();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDirectMessagesWith(arg0: Principal): Promise<Array<PrivateMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessagesWith(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessagesWith(arg0);
            return result;
        }
    }
    async getInvites(): Promise<Array<Invite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvites();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvites();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getResourceCategories(): Promise<Array<ResourceCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceCategories();
            return result;
        }
    }
    async getResourceEntries(): Promise<Array<ResourceEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceEntries();
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfiles();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async moveTaskToResourceCategory(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveTaskToResourceCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveTaskToResourceCategory(arg0, arg1);
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return result;
        }
    }
    async renameBucket(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameBucket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameBucket(arg0, arg1);
            return result;
        }
    }
    async renameResourceCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameResourceCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameResourceCategory(arg0, arg1);
            return result;
        }
    }
    async revokeInvite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInvite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendPrivateMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPrivateMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPrivateMessage(arg0, arg1);
            return result;
        }
    }
    async toggleTaskCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompleted(arg0);
            return result;
        }
    }
    async updateLastSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen();
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CompanyEntryCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyEntryCategory): CompanyEntryCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CompanyEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyEntry): CompanyEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_InviteStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteStatus): InviteStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Invite_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invite): Invite {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    website_url: string;
    username: string;
    password: string;
    name: string;
    category: _CompanyEntryCategory;
}): {
    id: bigint;
    website_url: string;
    username: string;
    password: string;
    name: string;
    category: CompanyEntryCategory;
} {
    return {
        id: value.id,
        website_url: value.website_url,
        username: value.username,
        password: value.password,
        name: value.name,
        category: from_candid_CompanyEntryCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InviteStatus;
    token: string;
    createdAt: _Time;
}): {
    status: InviteStatus;
    token: string;
    createdAt: Time;
} {
    return {
        status: from_candid_InviteStatus_n17(_uploadFile, _downloadFile, value.status),
        token: value.token,
        createdAt: value.createdAt
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignee: _Assignee;
    title: string;
    creator: Principal;
    completed: boolean;
    bucketId: [] | [bigint];
    description: string;
    timestamp: _Time;
}): {
    id: bigint;
    assignee: Assignee;
    title: string;
    creator: Principal;
    completed: boolean;
    bucketId?: bigint;
    description: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        assignee: value.assignee,
        title: value.title,
        creator: value.creator,
        completed: value.completed,
        bucketId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.bucketId)),
        description: value.description,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    labs: null;
} | {
    insurance: null;
} | {
    dental_supply: null;
}): CompanyEntryCategory {
    return "labs" in value ? CompanyEntryCategory.labs : "insurance" in value ? CompanyEntryCategory.insurance : "dental_supply" in value ? CompanyEntryCategory.dental_supply : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    revoked: null;
} | {
    used: null;
}): InviteStatus {
    return "active" in value ? InviteStatus.active : "revoked" in value ? InviteStatus.revoked : "used" in value ? InviteStatus.used : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invite>): Array<Invite> {
    return value.map((x)=>from_candid_Invite_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompanyEntry>): Array<CompanyEntry> {
    return value.map((x)=>from_candid_CompanyEntry_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CompanyEntryCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyEntryCategory): _CompanyEntryCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyEntryCategory): {
    labs: null;
} | {
    insurance: null;
} | {
    dental_supply: null;
} {
    return value == CompanyEntryCategory.labs ? {
        labs: null
    } : value == CompanyEntryCategory.insurance ? {
        insurance: null
    } : value == CompanyEntryCategory.dental_supply ? {
        dental_supply: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
